apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: 573509103763.dkr.ecr.us-west-2.amazonaws.com/spring-boot-java-application:latest
        ports:
        - containerPort: 8080